version: '3.0'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    depends_on:
      - db
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=public

  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}